name: PrecipitationOff
version: '${project.version}'
main: vodzinskiy.precipitationoff.PrecipitationOff
api-version: '1.20'
authors: [Vodzinskiy]

permissions:
  pptoff:
    default: true

commands:
  pptoff:
    usage: /<command>